# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ergebnis import Ergebnis  # noqa: F401,E501
from swagger_server import util


class ErgebnisArray(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ergebnisse: List[Ergebnis]=None):  # noqa: E501
        """ErgebnisArray - a model defined in Swagger

        :param ergebnisse: The ergebnisse of this ErgebnisArray.  # noqa: E501
        :type ergebnisse: List[Ergebnis]
        """
        self.swagger_types = {
            'ergebnisse': List[Ergebnis]
        }

        self.attribute_map = {
            'ergebnisse': 'ergebnisse'
        }
        self._ergebnisse = ergebnisse

    @classmethod
    def from_dict(cls, dikt) -> 'ErgebnisArray':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ergebnisArray of this ErgebnisArray.  # noqa: E501
        :rtype: ErgebnisArray
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ergebnisse(self) -> List[Ergebnis]:
        """Gets the ergebnisse of this ErgebnisArray.


        :return: The ergebnisse of this ErgebnisArray.
        :rtype: List[Ergebnis]
        """
        return self._ergebnisse

    @ergebnisse.setter
    def ergebnisse(self, ergebnisse: List[Ergebnis]):
        """Sets the ergebnisse of this ErgebnisArray.


        :param ergebnisse: The ergebnisse of this ErgebnisArray.
        :type ergebnisse: List[Ergebnis]
        """
        if ergebnisse is None:
            raise ValueError("Invalid value for `ergebnisse`, must not be `None`")  # noqa: E501

        self._ergebnisse = ergebnisse
