# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ErgebnisCreatePayload(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, disziplin_id: str=None, schueler_id: str=None, wert: float=None):  # noqa: E501
        """ErgebnisCreatePayload - a model defined in Swagger

        :param disziplin_id: The disziplin_id of this ErgebnisCreatePayload.  # noqa: E501
        :type disziplin_id: str
        :param schueler_id: The schueler_id of this ErgebnisCreatePayload.  # noqa: E501
        :type schueler_id: str
        :param wert: The wert of this ErgebnisCreatePayload.  # noqa: E501
        :type wert: float
        """
        self.swagger_types = {
            'disziplin_id': str,
            'schueler_id': str,
            'wert': float
        }

        self.attribute_map = {
            'disziplin_id': 'disziplin_id',
            'schueler_id': 'schueler_id',
            'wert': 'wert'
        }
        self._disziplin_id = disziplin_id
        self._schueler_id = schueler_id
        self._wert = wert

    @classmethod
    def from_dict(cls, dikt) -> 'ErgebnisCreatePayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ergebnisCreatePayload of this ErgebnisCreatePayload.  # noqa: E501
        :rtype: ErgebnisCreatePayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def disziplin_id(self) -> str:
        """Gets the disziplin_id of this ErgebnisCreatePayload.


        :return: The disziplin_id of this ErgebnisCreatePayload.
        :rtype: str
        """
        return self._disziplin_id

    @disziplin_id.setter
    def disziplin_id(self, disziplin_id: str):
        """Sets the disziplin_id of this ErgebnisCreatePayload.


        :param disziplin_id: The disziplin_id of this ErgebnisCreatePayload.
        :type disziplin_id: str
        """
        if disziplin_id is None:
            raise ValueError("Invalid value for `disziplin_id`, must not be `None`")  # noqa: E501

        self._disziplin_id = disziplin_id

    @property
    def schueler_id(self) -> str:
        """Gets the schueler_id of this ErgebnisCreatePayload.


        :return: The schueler_id of this ErgebnisCreatePayload.
        :rtype: str
        """
        return self._schueler_id

    @schueler_id.setter
    def schueler_id(self, schueler_id: str):
        """Sets the schueler_id of this ErgebnisCreatePayload.


        :param schueler_id: The schueler_id of this ErgebnisCreatePayload.
        :type schueler_id: str
        """
        if schueler_id is None:
            raise ValueError("Invalid value for `schueler_id`, must not be `None`")  # noqa: E501

        self._schueler_id = schueler_id

    @property
    def wert(self) -> float:
        """Gets the wert of this ErgebnisCreatePayload.


        :return: The wert of this ErgebnisCreatePayload.
        :rtype: float
        """
        return self._wert

    @wert.setter
    def wert(self, wert: float):
        """Sets the wert of this ErgebnisCreatePayload.


        :param wert: The wert of this ErgebnisCreatePayload.
        :type wert: float
        """
        if wert is None:
            raise ValueError("Invalid value for `wert`, must not be `None`")  # noqa: E501

        self._wert = wert
