# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ErgebnisUpdatePayload(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, wert: float=None):  # noqa: E501
        """ErgebnisUpdatePayload - a model defined in Swagger

        :param wert: The wert of this ErgebnisUpdatePayload.  # noqa: E501
        :type wert: float
        """
        self.swagger_types = {
            'wert': float
        }

        self.attribute_map = {
            'wert': 'wert'
        }
        self._wert = wert

    @classmethod
    def from_dict(cls, dikt) -> 'ErgebnisUpdatePayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ergebnisUpdatePayload of this ErgebnisUpdatePayload.  # noqa: E501
        :rtype: ErgebnisUpdatePayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def wert(self) -> float:
        """Gets the wert of this ErgebnisUpdatePayload.


        :return: The wert of this ErgebnisUpdatePayload.
        :rtype: float
        """
        return self._wert

    @wert.setter
    def wert(self, wert: float):
        """Sets the wert of this ErgebnisUpdatePayload.


        :param wert: The wert of this ErgebnisUpdatePayload.
        :type wert: float
        """

        self._wert = wert
