# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.riege import Riege  # noqa: F401,E501
from swagger_server import util


class RiegeArray(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, riegen: List[Riege]=None):  # noqa: E501
        """RiegeArray - a model defined in Swagger

        :param riegen: The riegen of this RiegeArray.  # noqa: E501
        :type riegen: List[Riege]
        """
        self.swagger_types = {
            'riegen': List[Riege]
        }

        self.attribute_map = {
            'riegen': 'riegen'
        }
        self._riegen = riegen

    @classmethod
    def from_dict(cls, dikt) -> 'RiegeArray':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The riegeArray of this RiegeArray.  # noqa: E501
        :rtype: RiegeArray
        """
        return util.deserialize_model(dikt, cls)

    @property
    def riegen(self) -> List[Riege]:
        """Gets the riegen of this RiegeArray.


        :return: The riegen of this RiegeArray.
        :rtype: List[Riege]
        """
        return self._riegen

    @riegen.setter
    def riegen(self, riegen: List[Riege]):
        """Sets the riegen of this RiegeArray.


        :param riegen: The riegen of this RiegeArray.
        :type riegen: List[Riege]
        """

        self._riegen = riegen
