# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.schueler import Schueler  # noqa: F401,E501
from swagger_server import util


class Schuelers(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, schuelers: List[Schueler]=None):  # noqa: E501
        """Schuelers - a model defined in Swagger

        :param schuelers: The schuelers of this Schuelers.  # noqa: E501
        :type schuelers: List[Schueler]
        """
        self.swagger_types = {
            'schuelers': List[Schueler]
        }

        self.attribute_map = {
            'schuelers': 'schuelers'
        }
        self._schuelers = schuelers

    @classmethod
    def from_dict(cls, dikt) -> 'Schuelers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The schuelers of this Schuelers.  # noqa: E501
        :rtype: Schuelers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def schuelers(self) -> List[Schueler]:
        """Gets the schuelers of this Schuelers.


        :return: The schuelers of this Schuelers.
        :rtype: List[Schueler]
        """
        return self._schuelers

    @schuelers.setter
    def schuelers(self, schuelers: List[Schueler]):
        """Sets the schuelers of this Schuelers.


        :param schuelers: The schuelers of this Schuelers.
        :type schuelers: List[Schueler]
        """
        if schuelers is None:
            raise ValueError("Invalid value for `schuelers`, must not be `None`")  # noqa: E501

        self._schuelers = schuelers
